ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: clusterissuer-binbash-cert-manager-clusterissuer
    kubernetes.io/ingress.class: private-apps
    kubernetes.io/tls-acme: "true"
  paths: ['/']
  hosts:
    - testapp.us-east-1.devstg.aws.binbash.com.ar
    - testapp.devstg.aws.binbash.com.ar
  tls:
    - secretName: py-az-tls
      hosts:
        - testapp.us-east-1.devstg.aws.binbash.com.ar
        - testapp.devstg.aws.binbash.com.ar
