#
# Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/application.yaml
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-sock-shop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/binbashar/le-demo-apps.git
    targetRevision: HEAD
    path: sock-shop/kubernetes
  
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-sock-shop

  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
