kind: ServiceAccount
apiVersion: v1
metadata:
  name: emoji
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: emoji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
  strategy:
    blueGreen: 
      activeService: emoji-svc
      previewService: emoji-svc-preview
      previewReplicaCount: 1
  template:
    metadata:
      labels:
        app: emoji-svc
    spec:
      serviceAccountName: emoji
      containers:
      - name: emoji-svc
        image: 763606934258.dkr.ecr.us-east-1.amazonaws.com/emojivoto-emoji-svc:tag
        env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc-preview
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: clusterissuer-binbash-cert-manager-clusterissuer
    kubernetes.io/ingress.class: private-apps
    kubernetes.io/tls-acme: "true"
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emoji
  name: emoji-svc-ingress
spec:
  rules:
  - host: emoji.aws.binbash.com.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emoji-svc
            port:
              number: 8080
  - host: preview.emoji.aws.binbash.com.ar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emoji-svc-preview
            port:
              number: 8080
  tls:
  - hosts:
    - emoji.aws.binbash.com.ar
    - preview.emoji.aws.binbash.com.ar
    secretName: emoji-svc-private-tls
