apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

openapi:
  path: k8s_kustomize_schema.json

resources:
  - emoji-api.yml
  - voting-api.yml
  - web.yml
