apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - rollout-transform.yaml

openapi:
  path: argo_all_k8s_kustomize_schema.json

resources:
  - emoji-api.yml
  - voting-api.yml
  - web.yml
