---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v3
  name: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-svc
      version: v3
  template:
    metadata:
      labels:
        app: voting-svc
        version: v3
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: 763606934258.dkr.ecr.us-east-1.amazonaws.com/demo-apps:emojivoto-voting-svc-v3
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: voting
  strategy:
    blueGreen: 
      activeService: voting-svc-active
      previewService: voting-svc-preview
      autoPromotionEnabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc-active
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: voting-svc
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc-preview
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: voting-svc