apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emoji-voto-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secrets-manager
    kind: ClusterSecretStore
  target:
    name: TestSecret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /k8s-eks/secretForTesting
  # data:
  # - secretKey: SecretSecret
  #   remoteRef:
  #     key: /k8s-eks/secretForTesting
  #     property: testSecret

