apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emoji-voto-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secrets-manager
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  - secretKey: SecretSecret
    remoteRef:
      key: /k8s-eks/secretForTesting
      property: testSecret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emoji-voto-parameters
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-parameter-store
    kind: ClusterSecretStore
  target:
    name: test-parameter
  data:
  - secretKey: SecretParameter
    remoteRef:
      key: /k8s-eks/parameterForTesting
      property: testParameter