apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: emoji-voto-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      role: arn:aws:iam::763606934258:role/appsdevstg-external-secrets
