apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-client
  project: default
  source:
    repoURL: https://github.com/binbashar/le-demo-apps
    targetRevision: argocd
    path: argocd/app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
      - "Prune=true"
    # retry:
    #   backoff:
    #     duration: 5s
    #     factor: 2
    #     maxDuration: 3m0s
    #   limit: 2
