apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: "ArgoCD Project for {{ .Values.global.name }}"

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
