apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
labels:
- pairs:
    env: devstg
resources:
- ../../base
patches:
- path: web.yml
- target:
    kind: Ingress
    name: emoji-svc-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: emoji.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/tls/0/hosts/0
      value: emoji.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/rules/1/host
      value: preview.emoji.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/tls/0/hosts/1
      value: preview.emoji.demo.devstg.aws.binbash.com.ar
- target:
    kind: Ingress
    name: voting-svc-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: voting.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/tls/0/hosts/0
      value: voting.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/rules/1/host
      value: preview.voting.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/tls/0/hosts/1
      value: preview.voting.demo.devstg.aws.binbash.com.ar
- target:
    kind: Ingress
    name: web-svc-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: web.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/tls/0/hosts/0
      value: web.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/rules/1/host
      value: preview.web.demo.devstg.aws.binbash.com.ar
    - op: replace
      path: /spec/tls/0/hosts/1
      value: preview.web.demo.devstg.aws.binbash.com.ar
images:
- name: 763606934258.dkr.ecr.us-east-1.amazonaws.com/emojivoto-emoji-svc
  newTag: 16-0318722
- name: 763606934258.dkr.ecr.us-east-1.amazonaws.com/emojivoto-voting-svc
  newTag: 16-0318722
- name: 763606934258.dkr.ecr.us-east-1.amazonaws.com/emojivoto-web
  newTag: 16-0318722
