apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.prefix }}-root
  namespace: {{ .Values.global.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.destination.namespace }}
  project: {{ .Values.global.prefix }}
  source:
    repoURL: {{ .Values.rootApp.source.repoURL }}
    targetRevision: {{ .Values.rootApp.source.targetRevision }}
    path: {{ .Values.rootApp.source.path }}
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - "CreateNamespace=true"
  #   - "Prune=true"
