apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
{{- if .Values.catalogue.annotations }}
      annotations:
{{ toYaml .Values.catalogue.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: catalogue
        image: {{ .Values.catalogue.image }}
{{- if .Values.catalogue.command }}
        command: {{ .Values.catalogue.command }}
{{- end }}
{{- if .Values.catalogue.args }}
        args: {{ .Values.catalogue.args }}
{{- end }}
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: catalogue
