{{ if .Values.catalogueMigrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: catalogue-migrations-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
{{ toYaml .Values.catalogueMigrations.annotations | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: weaveworksdemos/catalogue-db:0.3.0
        command:
        - "/bin/bash"
        args:
        - "/app/migrations.sh"
        volumeMounts:
        - mountPath: /app
          readOnly: true
          name: migrations-files
      volumes:
      - name: migrations-files
        configMap:
          name: catalogue-migrations-files
          items:
          - key: migrations.sh
            path: migrations.sh
          - key: dump.sql
            path: dump.sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-migrations-files
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
data:
  migrations.sh: |
    #!/bin/bash
    source /vault/secrets/env
    printenv
    cat <<EOF > /docker-entrypoint-initdb.d/my.cnf
    [client]
    host="$DB_HOST"
    user="$DB_USER"
    password="$DB_PASS"
    database="$DB_NAME"
    EOF
    #cat /docker-entrypoint-initdb.d/my.cnf
    #cp /docker-entrypoint-initdb.d/dump.sql /tmp/
    #sed -i -e "s/CREATE\sUSER/\-\- CREATE USER/" /tmp/dump.sql
    #sed -i -e "s/GRANT/\-\- GRANT/" /tmp/dump.sql
    # while :;do hostname;sleep 15;done
    mysql --defaults-extra-file=/docker-entrypoint-initdb.d/my.cnf < /app/dump.sql
  dump.sql: |
    CREATE TABLE IF NOT EXISTS sock (
      sock_id varchar(40) NOT NULL, 
      name varchar(20), 
      description varchar(200), 
      price float, 
      count int, 
      image_url_1 varchar(40), 
      image_url_2 varchar(40), 
      PRIMARY KEY(sock_id)
    );

    CREATE TABLE IF NOT EXISTS tag (
      tag_id MEDIUMINT NOT NULL AUTO_INCREMENT, 
      name varchar(20), 
      PRIMARY KEY(tag_id)
    );

    CREATE TABLE IF NOT EXISTS sock_tag (
      sock_id varchar(40), 
      tag_id MEDIUMINT NOT NULL, 
      FOREIGN KEY (sock_id) 
        REFERENCES sock(sock_id), 
      FOREIGN KEY(tag_id)
        REFERENCES tag(tag_id)
    );

    INSERT IGNORE INTO sock VALUES ("a0a4f044-b040-410d-8ead-4de0446aec7e", "BB Nerd leg", "For all those leg lovers out there. A perfect example of a swivel chair trained calf. Meticulously trained on a diet of sitting and Pina Coladas. Phwarr...", 7.99, 115, "/catalogue/images/bit_of_leg_1.jpeg", "/catalogue/images/bit_of_leg_2.jpeg");
    INSERT IGNORE INTO sock VALUES ("808a2de1-1aaa-4c25-a9b9-6612e8f29a38", "BB Crossed", "A mature sock, crossed, with an air of nonchalance.",  17.32, 738, "/catalogue/images/cross_1.jpeg", "/catalogue/images/cross_2.jpeg");
    INSERT IGNORE INTO sock VALUES ("510a0d7e-8e83-4193-b483-e27e09ddc34d", "BB SuperSport XL", "Ready for action. Engineers: be ready to smash that next bug! Be ready, with these super-action-sport-masterpieces. This particular engineer was chased away from the office with a stick.",  15.00, 820, "/catalogue/images/puma_1.jpeg", "/catalogue/images/puma_2.jpeg");
    INSERT IGNORE INTO sock VALUES ("03fef6ac-1896-4ce8-bd69-b798f85c6e0b", "BB Holy", "Socks fit for a Messiah. You too can experience walking in water with these special edition beauties. Each hole is lovingly proggled to leave smooth edges. The only sock approved by a higher power.",  99.99, 1, "/catalogue/images/holy_1.jpeg", "/catalogue/images/holy_2.jpeg");
    INSERT IGNORE INTO sock VALUES ("d3588630-ad8e-49df-bbd7-3167f7efb246", "BB YouTube.sock", "We were not paid to sell this sock. It's just a bit geeky.",  10.99, 801, "/catalogue/images/youtube_1.jpeg", "/catalogue/images/youtube_2.jpeg");
    INSERT IGNORE INTO sock VALUES ("819e1fbf-8b7e-4f6d-811f-693534916a8b", "BB Figueroa", "enim officia aliqua excepteur esse deserunt quis aliquip nostrud anim",  14, 808, "/catalogue/images/WAT.jpg", "/catalogue/images/WAT2.jpg");
    INSERT IGNORE INTO sock VALUES ("zzz4f044-b040-410d-8ead-4de0446aec7e", "BB Classic", "Keep it simple.",  12, 127, "/catalogue/images/classic.jpg", "/catalogue/images/classic2.jpg");
    INSERT IGNORE INTO sock VALUES ("3395a43e-2d88-40de-b95f-e00e1502085b", "BB Colourful", "proident occaecat irure et excepteur labore minim nisi amet irure",  18, 438, "/catalogue/images/colourful_socks.jpg", "/catalogue/images/colourful_socks.jpg");
    INSERT IGNORE INTO sock VALUES ("837ab141-399e-4c1f-9abc-bace40296bac", "BB Cat socks", "consequat amet cupidatat minim laborum tempor elit ex consequat in",  15, 175, "/catalogue/images/catsocks.jpg", "/catalogue/images/catsocks2.jpg");

    INSERT IGNORE INTO tag (name) VALUES ("brown");
    INSERT IGNORE INTO tag (name) VALUES ("geek");
    INSERT IGNORE INTO tag (name) VALUES ("formal");
    INSERT IGNORE INTO tag (name) VALUES ("blue");
    INSERT IGNORE INTO tag (name) VALUES ("skin");
    INSERT IGNORE INTO tag (name) VALUES ("red");
    INSERT IGNORE INTO tag (name) VALUES ("action");
    INSERT IGNORE INTO tag (name) VALUES ("sport");
    INSERT IGNORE INTO tag (name) VALUES ("black");
    INSERT IGNORE INTO tag (name) VALUES ("magic");
    INSERT IGNORE INTO tag (name) VALUES ("green");

    INSERT IGNORE INTO sock_tag VALUES ("a0a4f044-b040-410d-8ead-4de0446aec7e", "4");
    INSERT IGNORE INTO sock_tag VALUES ("a0a4f044-b040-410d-8ead-4de0446aec7e", "5");
    INSERT IGNORE INTO sock_tag VALUES ("808a2de1-1aaa-4c25-a9b9-6612e8f29a38", "4");
    INSERT IGNORE INTO sock_tag VALUES ("808a2de1-1aaa-4c25-a9b9-6612e8f29a38", "6");
    INSERT IGNORE INTO sock_tag VALUES ("808a2de1-1aaa-4c25-a9b9-6612e8f29a38", "7");
    INSERT IGNORE INTO sock_tag VALUES ("808a2de1-1aaa-4c25-a9b9-6612e8f29a38", "3");
    INSERT IGNORE INTO sock_tag VALUES ("510a0d7e-8e83-4193-b483-e27e09ddc34d", "8");
    INSERT IGNORE INTO sock_tag VALUES ("510a0d7e-8e83-4193-b483-e27e09ddc34d", "9");
    INSERT IGNORE INTO sock_tag VALUES ("510a0d7e-8e83-4193-b483-e27e09ddc34d", "3");
    INSERT IGNORE INTO sock_tag VALUES ("03fef6ac-1896-4ce8-bd69-b798f85c6e0b", "10");
    INSERT IGNORE INTO sock_tag VALUES ("03fef6ac-1896-4ce8-bd69-b798f85c6e0b", "7");
    INSERT IGNORE INTO sock_tag VALUES ("d3588630-ad8e-49df-bbd7-3167f7efb246", "2");
    INSERT IGNORE INTO sock_tag VALUES ("d3588630-ad8e-49df-bbd7-3167f7efb246", "3");
    INSERT IGNORE INTO sock_tag VALUES ("819e1fbf-8b7e-4f6d-811f-693534916a8b", "3");
    INSERT IGNORE INTO sock_tag VALUES ("819e1fbf-8b7e-4f6d-811f-693534916a8b", "11");
    INSERT IGNORE INTO sock_tag VALUES ("819e1fbf-8b7e-4f6d-811f-693534916a8b", "4");
    INSERT IGNORE INTO sock_tag VALUES ("zzz4f044-b040-410d-8ead-4de0446aec7e", "1");
    INSERT IGNORE INTO sock_tag VALUES ("zzz4f044-b040-410d-8ead-4de0446aec7e", "11");
    INSERT IGNORE INTO sock_tag VALUES ("3395a43e-2d88-40de-b95f-e00e1502085b", "1");
    INSERT IGNORE INTO sock_tag VALUES ("3395a43e-2d88-40de-b95f-e00e1502085b", "4");
    INSERT IGNORE INTO sock_tag VALUES ("837ab141-399e-4c1f-9abc-bace40296bac", "1");
    INSERT IGNORE INTO sock_tag VALUES ("837ab141-399e-4c1f-9abc-bace40296bac", "11");
    INSERT IGNORE INTO sock_tag VALUES ("837ab141-399e-4c1f-9abc-bace40296bac", "3");
{{ end }}
