apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/namespace: "admin"
      #   vault.hashicorp.com/role: "demoapps_sockshop_readonly"
      #   vault.hashicorp.com/agent-inject-secret-env: "secrets/data/le-demo-apps/sock-shop/devstg"
      #   vault.hashicorp.com/agent-inject-template-env: |
      #     {{ with secret "secrets/data/le-demo-apps/sock-shop/devstg" -}}
      #       export DSN="{{ .Data.data.DSN }}"
      #       export UUID="{{ .Data.data.UUID }}"
      #     {{- end }}
    spec:
      containers:
      - name: catalogue
        image: weaveworksdemos/catalogue:0.3.5
        # command: ["/bin/sh"]
        # args: ["-c", "source /vault/secrets/env && rm /vault/secrets/env && echo UUID=$UUID && /app -port=80 -DSN=$DSN"]
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: catalogue
