carts:
  image: weaveworksdemos/carts:0.4.8

cataloguedb:
  enabled: true
  image: weaveworksdemos/catalogue-db:0.3.0

catalogue:
  image: weaveworksdemos/catalogue:0.3.5  
  annotations: {}

frontend:
  image: weaveworksdemos/front-end:0.3.12
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: clusterissuer-binbash-cert-manager-clusterissuer
      kubernetes.io/ingress.class: ingress-nginx-private
      kubernetes.io/tls-acme: "true"
    paths: ['/']
    hosts:
      - sockshopapp.devstg.aws.binbash.com.ar
    tls:
      - secretName: front-end-tls
        hosts:
          - sockshopapp.devstg.aws.binbash.com.ar

orders:
  image: weaveworksdemos/orders:0.4.7

payment:
  image: weaveworksdemos/payment:0.4.3

queuemaster:
  image: weaveworksdemos/queue-master:0.3.1

shipping:
  image: weaveworksdemos/shipping:0.4.8

userdb:
  image: weaveworksdemos/user-db:0.4.0

user:
  image: weaveworksdemos/user:0.4.7
  
# Run migrations -- only needed when using an external mysql service
cataloguemigrations:
  enabled: false
