#
# Default values for sock-shop with AWS integration.
#

# Annotate the service to enable secrets injection through Vault Agent
catalogue:
  image: weaveworksdemos/catalogue:0.3.5
  annotations: &catalogueAnnotations
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/namespace: "admin"
    vault.hashicorp.com/role: "demoapps_sockshop_readonly"
    vault.hashicorp.com/agent-inject-secret-env: "secrets/data/demoapps/devstg/sock-shop"
    vault.hashicorp.com/agent-inject-template-env: |
      {{ with secret "secrets/data/demoapps/devstg/sock-shop" -}}
        export DSN="{{ .Data.data.DSN }}"
        export DB_HOST="{{ .Data.data.DB_HOST }}"
        export DB_NAME="{{ .Data.data.DB_NAME }}"
        export DB_USER="{{ .Data.data.DB_USER }}"
        export DB_PASS="{{ .Data.data.DB_PASS }}"
      {{- end }}

# Run migrations -- we will use an external mysql service (RDS)
cataloguemigrations:
  enabled: true
  annotations: *catalogueAnnotations

# Disable the in-cluster DB service
cataloguedb:
  enabled: false
