#
# Default values for sock-shop with AWS integration.
#

catalogue:
  image: weaveworksdemos/catalogue:0.3.5
  command:
  - "/bin/sh"
  - "-c"
  # args: [". /vault/secrets/env && printenv && /app -port=80 -DSN=$DSN"]
  args:
  - ". /vault/secrets/env && printenv && echo 'OK'"

  annotations: &catalogueAnnotations
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/namespace: "admin"
    vault.hashicorp.com/role: "demoapps_sockshop_readonly"
    vault.hashicorp.com/agent-inject-secret-env: "secrets/data/demoapps/devstg/sock-shop"
    vault.hashicorp.com/agent-inject-template-env: |
      {{ with secret "secrets/data/demoapps/devstg/sock-shop" -}}
        export DSN="{{ .Data.data.DSN }}"
      {{- end }}

catalogueMigrations:
  enabled: true
  annotations: *catalogueAnnotations

cataloguedb:
  enabled: false
